name: buttons_tabbar_plus
description: A Flutter package that implements a TabBar where each label is a toggle button.
version: 1.3.16
homepage: 
repository: https://github.com/Alyssonpp/buttons_tabbar_plus

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
